#!/usr/bin/env python

import sys
import signal

from ServerTrack.service import ServerTrack





def main(args):
	print >>sys.stderr, 'Initiating service' 
	service = ServerTrack()
	service.run()


if __name__ == '__main__':
	sys.exit(main(sys.argv))