#!/usr/bin/env python

import sys
import signal

from ServerTrack import daemon

service = daemon.ServerTrack()

def quit(sig, frame):
	print >>sys.stderr, 'Terminating service'
	service.stop()

def main(args):
	print >>sys.stderr, 'Initiating service' 
	service.run()
	signal.signal(signal.SIGINT, quit)


if __name__ == '__main__':
	sys.exit(main(sys.argv))